/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Icon, Image, Text, View } from "@aws-amplify/ui-react";
export default function Component3(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1440px"
      height="1320px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...rest}
      {...getOverrideProps(overrides, "Component3")}
    >
      <View
        width="1440px"
        height="100px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="92.42%"
        left="0%"
        right="0%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.5)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(194,249,160,1)"
        {...getOverrideProps(overrides, "Rectangle 13")}
      ></View>
      <View
        width="200px"
        height="64px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="32.73%"
        bottom="62.42%"
        left="43.06%"
        right="43.06%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.5)"
        borderRadius="30px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(194,249,160,1)"
        {...getOverrideProps(overrides, "Rectangle 14")}
      ></View>
      <View
        width="970px"
        height="312px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="49.09%"
        bottom="27.27%"
        left="16.32%"
        right="16.32%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.5)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(194,249,160,1)"
        {...getOverrideProps(overrides, "Rectangle 15")}
      ></View>
      <View
        width="970px"
        height="312px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="76.36%"
        bottom="0%"
        left="16.32%"
        right="16.32%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.5)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(194,249,160,1)"
        {...getOverrideProps(overrides, "Rectangle 29")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="30px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="36.30681610107422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        textDecoration="underline"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="51.52%"
        bottom="45.76%"
        left="31.6%"
        right="53.54%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Lee Chong Wei"
        {...getOverrideProps(overrides, "Lee Chong Wei")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="30px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="36.30681610107422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="33.79%"
        bottom="63.48%"
        left="46.53%"
        right="46.6%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Search"
        {...getOverrideProps(overrides, "Search")}
      ></Text>
      <View
        width="200px"
        height="50px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="66.36%"
        bottom="29.85%"
        left="31.81%"
        right="54.31%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.5)"
        borderRadius="30px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,102,1)"
        {...getOverrideProps(overrides, "Rectangle 27")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="30px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="36.30681610107422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="66.89%"
        bottom="30.38%"
        left="36.04%"
        right="58.61%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Invite"
        {...getOverrideProps(overrides, "Invite")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="40px"
        fontWeight="700"
        color="rgba(64,0,103,1)"
        lineHeight="48.409088134765625px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="12.8%"
        bottom="83.56%"
        left="41.53%"
        right="41.18%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Find a Player"
        {...getOverrideProps(overrides, "Find a Player")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="18.18%"
        bottom="80%"
        left="35.28%"
        right="52.08%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Choose a location:"
        {...getOverrideProps(overrides, "Choose a location:")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="21.21%"
        bottom="76.97%"
        left="35.28%"
        right="52.22%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Match Preference:"
        {...getOverrideProps(overrides, "Match Preference:")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="24.24%"
        bottom="73.94%"
        left="35.28%"
        right="57.5%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Skill Level:"
        {...getOverrideProps(overrides, "Skill Level:")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="27.27%"
        bottom="70.91%"
        left="35.28%"
        right="61.18%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Goal:"
        {...getOverrideProps(overrides, "Goal:")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="55.15%"
        bottom="43.03%"
        left="31.81%"
        right="46.18%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Match Preference: Singles Player"
        {...getOverrideProps(overrides, "Match Preference: Singles Player")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.58%"
        bottom="40.61%"
        left="31.81%"
        right="54.03%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Skill Level: Advanced"
        {...getOverrideProps(overrides, "Skill Level: Advanced")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="60%"
        bottom="38.18%"
        left="31.81%"
        right="52.85%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Location: San Jose, CA "
        {...getOverrideProps(overrides, "Location: San Jose, CA")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="62.42%"
        bottom="35.76%"
        left="31.81%"
        right="36.94%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Goal: Competitive, looking for a training partner"
        {...getOverrideProps(
          overrides,
          "Goal: Competitive, looking for a training partner"
        )}
      ></Text>
      <View
        width="200px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="18.18%"
        bottom="80%"
        left="48.75%"
        right="37.36%"
        border="1px SOLID rgba(0,0,0,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 23")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="18.18%"
        bottom="80%"
        left="49.79%"
        right="43.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="South Bay"
        {...getOverrideProps(overrides, "South Bay")}
      ></Text>
      <View
        width="200px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="21.21%"
        bottom="76.97%"
        left="48.75%"
        right="37.36%"
        border="1px SOLID rgba(0,0,0,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 24")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="21.21%"
        bottom="76.97%"
        left="49.79%"
        right="42.99%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Singles 1v1"
        {...getOverrideProps(overrides, "Singles 1v1")}
      ></Text>
      <View
        width="200px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="24.24%"
        bottom="73.94%"
        left="43.19%"
        right="42.92%"
        border="1px SOLID rgba(0,0,0,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 25")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="24.24%"
        bottom="73.94%"
        left="44.24%"
        right="49.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Advanced"
        {...getOverrideProps(overrides, "Advanced")}
      ></Text>
      <View
        width="505px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="27.27%"
        bottom="70.91%"
        left="39.86%"
        right="25.07%"
        border="1px SOLID rgba(0,0,0,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 26")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="27.27%"
        bottom="70.91%"
        left="40.9%"
        right="31.25%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Competitive, Looking for a training partner"
        {...getOverrideProps(
          overrides,
          "Competitive, Looking for a training partner"
        )}
      ></Text>
      <Icon
        width="1228.5px"
        height="0px"
        viewBox={{ minX: 0, minY: 0, width: 1228.5, height: 1 }}
        paths={[
          {
            d: "M0 1.5L1228.5 1.5L1228.5 -1.5L0 -1.5L0 1.5Z",
            stroke: "rgba(212,206,206,1)",
            fillRule: "nonzero",
            strokeWidth: 3,
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="41.7%"
        bottom="58.3%"
        left="7.33%"
        right="7.36%"
        {...getOverrideProps(overrides, "Line 1")}
      ></Icon>
      <Text
        fontFamily="Inter"
        fontSize="24px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="29.045454025268555px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.17%"
        bottom="53.64%"
        left="8.68%"
        right="78.68%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="3 Results Found"
        {...getOverrideProps(overrides, "3 Results Found")}
      ></Text>
      <Image
        width="10.07%"
        height="10.98%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="52.95%"
        bottom="36.06%"
        left="19.44%"
        right="70.49%"
        borderRadius="30px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "Rectangle 28")}
      ></Image>
      <Image
        width="4.93%"
        height="5.38%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="1.14%"
        bottom="93.48%"
        left="5.42%"
        right="89.65%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image 1")}
      ></Image>
      <Text
        fontFamily="Inter"
        fontSize="48px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="58.09090805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="1.59%"
        bottom="94.02%"
        left="11.04%"
        right="70.21%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="MatchMade"
        {...getOverrideProps(overrides, "MatchMade")}
      ></Text>
      <View
        width="200px"
        height="44px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2.05%"
        bottom="94.62%"
        left="81.25%"
        right="4.86%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.20000000298023224)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(183,216,255,1)"
        {...getOverrideProps(overrides, "Rectangle 16")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="36px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="43.568180084228516px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="2.05%"
        bottom="94.62%"
        left="83.54%"
        right="7.15%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sign Up"
        {...getOverrideProps(overrides, "Sign Up")}
      ></Text>
      <View
        width="255px"
        height="44px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2.2%"
        bottom="94.47%"
        left="62.15%"
        right="20.14%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.20000000298023224)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(183,216,255,1)"
        {...getOverrideProps(overrides, "Rectangle 17")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="36px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="43.568180084228516px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="2.2%"
        bottom="94.47%"
        left="63.82%"
        right="21.81%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Find Players"
        {...getOverrideProps(overrides, "Find Players")}
      ></Text>
      <View
        width="145px"
        height="44px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2.2%"
        bottom="94.47%"
        left="50.69%"
        right="39.24%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.20000000298023224)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(183,216,255,1)"
        {...getOverrideProps(overrides, "Rectangle 18")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="36px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="43.568180084228516px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="2.05%"
        bottom="94.62%"
        left="51.74%"
        right="40.28%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Events"
        {...getOverrideProps(overrides, "Events")}
      ></Text>
      <View
        width="145px"
        height="44px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2.27%"
        bottom="94.39%"
        left="39.24%"
        right="50.69%"
        boxShadow="0px 2px 15px rgba(0, 0, 0, 0.20000000298023224)"
        borderRadius="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(183,216,255,1)"
        {...getOverrideProps(overrides, "Rectangle 20")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="36px"
        fontWeight="400"
        color="rgba(64,0,103,1)"
        lineHeight="43.568180084228516px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="2.12%"
        bottom="94.55%"
        left="40.76%"
        right="52.22%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Home"
        {...getOverrideProps(overrides, "Home")}
      ></Text>
    </View>
  );
}
